apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox-pv  # Створюємо Persistent Volume для збереження логів
spec:
  capacity:
    storage: 1Gi  # Обсяг пам'яті
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/data"