apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc  # Створюємо Persistent Volume Claim для зв'язку з PV
  namespace: busybox-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath